variables:
    IMAGE: frontier-service
    VERSION: '1.11'
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

# Make the gradle wrapper executable. This essentially downloads a copy of
# Gradle to build the project with.
# https://docs.gradle.org/current/userguide/gradle_wrapper.html
# It is expected that any modern gradle project has a wrapper
before_script:
  - chmod +x gradlew

include:
  - project : 'ci-tools/container-image-ci-templates'
    file : 'kaniko-image.gitlab-ci.yml'
    ref: master

stages:
 - package_application
 - push
 - build_rpm

package_cern_application:
  stage: package_application
  image: registry.cern.ch/docker.io/eclipse-temurin:17-alpine
  script:
   - ./gradlew clean build -x test
  allow_failure: false
  artifacts:
   paths:
   - ./build/dist/Frontier.war

# Can be used to test packaging helm chart, before merging to master for instance
#build_helm:
#  extends: .deploy_helm
#  stage: build
#  variables:
#    REGISTRY_CHART_PATH: registry.cern.ch/crest/charts


build_container_job:
  rules:
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event'
  stage: push
  extends: .build_kaniko
  variables:
    REGISTRY_IMAGE_PATH : "registry.cern.ch/crest/$IMAGE:$VERSION"
    CONTEXT_DIR: ""
    PUSH_IMAGE: "true"
    DOCKER_FILE_NAME: "Dockerfile"

build_rpm_job:
  stage: build_rpm
  image: registry.cern.ch/docker.io/almalinux:9
  before_script:
      - cp ./package-rpm/get-rpms.sh /tmp/get-rpms.sh
      - chmod +x /tmp/get-rpms.sh
      - /tmp/get-rpms.sh
      - cp ./package-rpm/frontier-tomcat.spec /tmp/rpms/frontier-tomcat/SPECS/frontier-tomcat.spec
  script:
    - cd /tmp/rpms/frontier-tomcat
    - pushd ./scripts; ../../scripts/rpmbuild_.sh; popd
  allow_failure: false
  artifacts:
    paths:
      - /tmp/rpms/frontier-tomcat/RPMS/noarch/frontier-tomcat-11.0.7_4.0-1.noarch.rpm

